 
import Asidebar from "@/components/admin/Asidebar";
// export const metadata = {
//   title: "AKTU Brand",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <div
       className='flex px-1.5' 
      >
        
          <div className=""> 
          <Asidebar />
        </div>
        
        {children}
         
        
        
      </div>
  );
}
