import React from "react";
import { ChevronDown } from "lucide-react";

const faqData = [
  {
    question: "What is GPT Resume?",
    answer:
      "GPT Resume is an AI-powered resume builder that helps you create a professional, tailored resume and cover letter in seconds. Just paste a job description, and our GPT engine customizes your resume based on it."
  },
  {
    question: "How does GPT Resume Builder work?",
    answer:
      "Simply paste the job description. GPT Resume instantly analyzes the job role and generates a new resume based on you profile, a personalized cover letter, and job-specific improvement tips — all within seconds."
  },
  {
    question: "Is GPT Resume free to use?",
    answer:
      "Yes! GPT Resume offers a free plan with essential features. "
  },
  {
    question: "Can I edit my AI-generated resume?",
    answer:
      "Absolutely! Every resume and cover letter generated by GPT Resume is fully editable. You can modify content before downloading or applying."
  },
  {
    question: "Is my data safe with GPT Resume?",
    answer:
      "Yes, 100%. GPT Resume processes everything locally in your browser — your data, resume, and job details are never stored or shared with any server."
  },
  {
    question: "Do I need to create an account to use GPT Resume?",
    answer:
      "Yes signup is required to start. You can build and download your resume instantly after it. However, creating an account helps you save and edit your resumes anytime."
  },
  {
    question: "Does GPT Resume only create resumes?",
    answer:
      "No! GPT Resume also generates professional cover letters, personalized improvement suggestions, and job-specific keywords to help you stand out."
  },
   
  {
    question: "Which formats can I download my GPT Resume in?",
    answer:
      "You can download your GPT Resume as PDF formats, making it easy to share or submit to employers directly."
  }
];

function Faq() {
  return (
    <section id="faq" className="max-w-3xl mx-auto py-12 px-4">
      <h2 className="text-3xl font-bold mb-8 text-center">
        Frequently Asked Questions
      </h2>

      {faqData.map((item, index) => (
        <details
          key={index}
          className="mb-4 border rounded-lg p-4 group open:shadow-md transition-all"
        >
          <summary className="cursor-pointer font-medium text-lg flex justify-between items-center">
            {item.question}
            <ChevronDown className="h-5 w-5 transition-transform group-open:rotate-180" />
          </summary>
          <p className="mt-2 text-[var(--color-muted-foreground)] leading-relaxed">
            {item.answer}
          </p>
        </details>
      ))}
    </section>
  );
}

export default Faq;
